name: Testing WorldHub Features

on: [push, pull_request]

jobs:
  check-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node. 20.x
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn

      - name: Run tests
        run: yarn test
